### ISSUE TITLE
Test installation on an environment without gcc

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer-test#132]
A user can use Chainer on an environment without gcc if he doesn't need CUDA.
Currently we always test chainer with gcc. We need to check such a environment.

**Comment by kmaehashi** [comment]
I think this issue can be closed, because Cython dependency is now isolated to cupy.

**Comment by unnonouno** [comment]
Instead we need to test cupy with an environment without gcc.

**Comment by niboshi** [comment]
Included in #177
