### ISSUE TITLE
Fix Failed Jenkins Jobs

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer-test#241]
We need to fix all tests on Jenkins first. It should be completed before starting development of new features.

Currently we have 7 failed jobs on Jenkins.

- [ ] chainer-test_master_cupy
- [ ] chainer_master_chainer
- [ ] chainer_master_chainer-install
- [ ] chainer_stable_chainer
- [ ] cupy_master_chainer
- [ ] cupy_master_cupy
- [ ] daily_master_chainer-shuffled
- [ ] daily_master_cupy-shuffled
- [ ] daily_stable_chainer-shuffled
- [ ] daily_stable_cupy-shuffled

### chainer-shuffled

- FAIL: test_choice_multinomial (test_generator.TestChoiceMultinomial)
```
(mismatch 66.6666666667%)
x: array([ 0.1978,  0.2926,  0.5096], dtype=float32)
y: array([ 0.2081,  0.2983,  0.4936], dtype=float32)
```

### chainer-shuffled-v2

- setuptools's bug
```
import six
ImportError: No module named 'six'
```

### chainer-test-test

- It should see cupy/cupy repo

```
21:37:45 ======================================================================
21:37:45 ERROR: test_concat_arrays_gpu (test_convert.TestConcatExamples)
21:37:45 ----------------------------------------------------------------------
21:37:45 Traceback (most recent call last):
21:37:45   File "/work/chainer/tests/chainer_tests/dataset_tests/test_convert.py", line 36, in test_concat_arrays_gpu
21:37:45     arrays = self.get_arrays_to_concat(cuda.cupy)
21:37:45 AttributeError: 'module' object has no attribute 'cupy'
```

---

As for test failures due to non-deterministic random numbers, this PR should fix them: https://github.com/cupy/cupy/pull/82

**Comment by mitmul** [comment]
## Known issue

- setuptools's bug

**Comment by unnonouno** [comment]
Currently it works.
