### ISSUE TITLE
Use environment variable for simplicity

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer-test#257]
I want to support environment variable for simplify command line options:
- CHAINER_TEST_CACHE: default value for `--cache`
- CHAINER_TEST_HTTP_PROXY:  default value for `--http-proxy`
- CHAINER_TEST_HTTPS_PROXY: default value for `--https-proxy`
- CHAINER_TEST_COVERALLS: default value for `--coveralls`

**Comment by kmaehashi** [comment]
Implemented via #260.
