### ISSUE TITLE
Avoid adjusting version numbers for shuffle tests

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer-test#396]
In shuffle tests, currently we are carefully adjusting version numbers for randomly-generated shuffle (combination) tests. For example:
https://github.com/chainer/chainer-test/blob/0e584339d6e77da164fc862be4f8d0f65d264c32/shuffle.py#L30-L39

However, it is ambiguous if two constraints are conflicting. I think it is better to just skip the generated combination if it is invalid, rather than tweaking the generated combination to work.

**Comment by toslunar** [comment]
Fixed by #535.
