### ISSUE TITLE
cannot open .so

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer-test#461]
```
./run_multi_test.py --base ubuntu16_py27 --cuda cuda75 --cudnn cudnn6 --nccl none --ideep 2.0 --numpy 1.13 --h5py 2.6 --theano 0.9 --pillow 3.4 --protobuf cpp-3 --type gpu
```
causes installation failures of
- CUDA
```
original error: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
- ~iDeep~
~`Reason: ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory`~

**Comment by toslunar** [comment]
`--enable-shared`?

**Comment by kmaehashi** [comment]
> original error: libcublas.so.9.0: cannot open shared object file: No such file or directory

I think this is the different problem (referring to CUDA 9.0 on `--cuda cuda75`)

**Comment by kmaehashi** [comment]
FYI: new ideep package will resolve this issue.
https://github.com/intel/ideep/issues/22

**Comment by kmaehashi** [comment]
> ```
> ./run_multi_test.py --base ubuntu16_py27 --cuda cuda75 --cudnn cudnn6 --nccl none --ideep 2.0 --numpy 1.13 --h5py 2.6 --theano 0.9 --pillow 3.4 --protobuf cpp-3 --type gpu
> ```

> ```
> original error: libcublas.so.9.0: cannot open shared object file: No such file or directory
> ```

As we dropped support for CUDA 7.5, let's reopen this issue if we find this error happen again.
