### ISSUE TITLE
Update Sphinx

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer-test#571]
See https://github.com/cupy/cupy/pull/3250#issuecomment-608280192

It seems blocked by chainer/chainer#8393.

**Comment by kmaehashi** [comment]
The version should align the version used in the RTD environment.
By default RTD uses `Sphinx<2`. I asked @takagi to update Sphinx used in RTD to `Sphinx<3` by adding it to `cupy/docs/requirements.txt`. After that we can bump version in chainer-test.
